FROM node:22-alpine as builder
WORKDIR /opt/app
COPY . .
RUN npm ci
RUN npm run build
RUN npm prune --omit=dev


FROM node:22-alpine 
WORKDIR /opt/app
COPY --from=builder /opt/app/dist ./dist
COPY --from=builder /opt/app/node_modules ./node_modules
COPY --from=builder /opt/app/public ./public
COPY --from=builder /opt/app/package.json .


EXPOSE 1337
CMD ["npm", "run", "start"]

