FROM node:22-alpine
WORKDIR /opt/app
COPY . .
RUN npm ci
RUN npm run build



FROM node:22-alpine 
WORKDIR /opt/app
COPY --from=builder /opt/app/dist ./dist
COPY --from=builder /opt/app/node_modules ./node_modules
COPY --from=builder /opt/app/public ./public

EXPOSE 1337
CMD ["npm","run","start"]


