name: CD

on:
  workflow_run:
    workflows: ["CI Build"]  # Must match the exact name of the upstream workflow
    types:
      - completed

jobs:
  deploy:
   runs-on: self-hosted
   steps:
      - name: Pull and run Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/strapi-deployment:latest
          docker stop projects-strapi-1 || true
          docker rm projects-strapi-1 || true
          docker run -d --name projects-strapi-1 -p 1337:1337 ${{ secrets.DOCKER_USERNAME }}/strapi-deployment:latest